services:
  gui:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    # image: moorelab/${IMAGE_NAME}-gui:${TAG}
    image: kragen-gui:${TAG}
    container_name: kragen-gui
    ports:
      - 3000:3000
    env_file:
      - .env
      - config/kragen.env
    volumes:
      - "./KRAGEN_Dashboard/Frontend:/app"
    working_dir: /app
    # command: bash -c "npm install && npm start"
