services:
  kragen:
    extends:
      file: docker-compose-setup.yml
      service: setup
    depends_on:
      - weaviate
    networks:
      - kragen-net

  weaviate:
    extends:
      file: docker-compose-weaviate.yml
      service: weaviate
    networks:
      - kragen-net

  backend:
    extends:
      file: docker-compose-backend.yml
      service: backend
    depends_on:
      - weaviate
    networks:
      - kragen-net

  gui:
    extends:
      file: docker-compose-gui.yml
      service: gui
    depends_on:
      - backend
    networks:
      - kragen-net

networks:
  kragen-net:
    driver: bridge
