version: '3'

services:
  kragen:
    extends:
      file: docker-compose-kragen.yml
      service: kragen
    depends_on:
      - weaviate

  weaviate:
    extends:
      file: docker-compose-weaviate.yml
      service: weaviate

  execgpt:
    extends:
      file: docker-compose-flask.yml
      service: execgpt
    depends_on:
      - weaviate
