services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    # image: moorelab/${IMAGE_NAME}:${TAG}
    image: kragen-server:${TAG}
    container_name: kragen-server
    ports:
      - 5050:5050
    volumes:
      - ./KRAGEN_Dashboard/Backend:/app
    working_dir: /app
    # entrypoint: ["python", "src/kragen.py"]
    env_file:
      - .env
      - config/kragen.env
